name: scanalyze
description: Aplikacja farmaceutyczna monitorująca składniki produktów.
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  http_parser: ^4.0.2

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  fluttertoast: ^8.2.1
  form_field_validator: ^1.1.0
  http: ^0.13.6
  shared_preferences: ^2.2.2
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
